### PR TITLE
Documentation fixes: * fix all but one doc warnings * align htmlhelp output name with other builders * some triial fixes.

### PR DESCRIPTION
**Pull request by mindw**

### CODE REVIEW

**Comment by luispedro** [comment]
Thank you, much appreciated!

**Comment by luispedro** [comment]
This caused a failure in read the docs

http://readthedocs.org/projects/mahotas/builds/4475236/


> ExtensionError: Could not import extension sphinx.ext.imgmath (exception: No module named imgmath)


Any reason we can not just switch back to `pngmath`?

**Comment by mindw** [comment]
The warning shows up in sphinx 1.4.x. Perhaps it's better to require sphinx 1.4.x in `readthedocs-requirements.txt`?

**Comment by luispedro** [comment]
That commit fixed it: https://readthedocs.org/projects/mahotas/builds/4483548/

So, I'll merge that into master and this is solved.

Thanks again.

**Pull request merged**
