### PR TITLE
Difference of Gaussian (DoG) edge detection added

### PR DESCRIPTION
**Pull request by wang1211**
Another edge detection method besides sobel. DoG can approximate Laplacian of Gaussian operator. It works as an efficient edge detector.

Will add a demo soon.

### CODE REVIEW

**Comment by luispedro** [comment]
Thank you. This looks very good.

I think I can merge as is and add a simple test later or you if you have a test, that'd be nice too (also needed: a credit for you in the `ChangeLog` file).

Is the `sigma2 = sigma1 * 1.001` relationship "standard" (used by other packages &c)? Should it be configurable?

**Comment by wang1211** [comment]
Thanks for the feedback. From what I have learned, 1.001 is not "standard" but a small `multiplier` such as 1.001 should make it approximate Laplacian of Gaussian better. However, after looking on the internet, I have also seen people using large `multiplier` such as 2. So a configurable parameter might be better in case users need it.

**Comment by luispedro** [comment]
Thank you again. I think this all looks good and I'm merging now.

**Comment by wang1211** [comment]
Cool. Thanks!

**Pull request merged**
