### PR TITLE
build python3.10 wheels on linux

### PR DESCRIPTION
**Pull request by colobas**
Build python3.10 wheels on linux and update python version used in action

### CODE REVIEW

**Comment by colobas** [comment]
I tested this manually in my fork to make sure it works (see the run [here](https://github.com/colobas/mahotas/actions/runs/4264926587))

**Comment by luispedro** [comment]
Thank you! I appreciate it. Especially that you tested it.

**Comment by colobas** [comment]
Thanks for the quick merge :smiley: 
Any idea when the next release will be?

**Comment by luispedro** [comment]
None planned, but I will just manually upload the wheels instead of waiting for the action to trigger

**Pull request merged**
